---
- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Upgrade packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  when: ansible_os_family == 'Debian'